language: go

go:
  - "1.10.x"

before_install:
  - make dep
  - go get -u golang.org/x/tools/...

script:
  - ./cmd/check_fmt.sh
  - ./cmd/check_imports.sh
  - make vet
  - make test
  - go test ./... -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)

os:
  - linux
  - osx

branches:
  except:
  - gh-pages
