build: off

clone_folder: c:\gopath\src\github.com\kasvith\kache

environment:
  GOPATH: c:\gopath

stack: go 1.10

before_test:
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - go version
  - go env
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure
  - go vet ./...

test_script:
  - go test -v ./...